spring:
  datasource:
    url: jdbc:postgresql://20.42.60.224:5432/digital-write
    username: postgres
    password: oykmxkagbpxkqmjp
  jpa:
    generate-ddl: true
    open-in-view: false

server:
  port: 9000