spring:
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379
  h2:
    console.enabled: true
  datasource:
    url: jdbc:h2:file:./data/testDB
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: update

logging:
  file:
    name: logs/my.log
  pattern:
    file: "[%thread] %logger : %msg%n"
  level:
    org: ERROR
    com.tcsp.digitalwrite: DEBUG


server:
  port: 9000