#spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5432/digital-write
#    username: postgres
#    password: 121art121
#  jpa:
#    generate-ddl: true
#    open-in-view: false
spring:
  h2:
    console.enabled: true
  datasource:
    url: jdbc:h2:file:./data/testDB
    username: sa
    password:
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
server:
  port: 9000