spring:
  h2:
    console.enabled: true
  datasource:
    url: jdbc:h2:file:./data/testDB
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
server:
  port: 9000